#!/usr/bin/env node

var _ = require("underscore"),
    split = require("split"),
    argv = require("minimist")(process.argv.slice(2)),
    fs = require("fs"),
    fields,
    stream,
    matches;

format = /(\d+\.\d+\.\d+\.\d+) - (\S+) \[(\d{2}\/\w+\/\d{4}:\d{2}:\d{2}:\d{2} [+-]\d{4})\] "(.+)" (\d{3}) (\d+) "(.+)" "(.+)"/;

if (argv._[0]) {
  stream = fs.createReadStream(argv._[0]);
} else {
  stream = process.stdin;
}

if (argv.p) {
  fields = argv.p.split(",");
}

stream.resume();
stream.setEncoding("utf8");
stream.pipe(split()).on("data", function(line) {
  matches = line.match(format);
  if (matches) {
    object = {}
    object.remoteAddr = matches[1];
    object.remoteUser = matches[2];
    object.localTime = matches[3];
    object.request = matches[4];
    object.status = matches[5];
    object.bodyBytesSent = matches[6];
    object.httpReferer = matches[7];
    object.httpUserAgent = matches[8];

    if (_.isArray(fields)) {
      if (fields.length > 1) {
        console.log(JSON.stringify(_.pick(object, fields)));
      } else {
        console.log(object[fields[0]]);
      }
    } else {
      console.log(JSON.stringify(object));
    }
  }
});
